//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.SPED.Resources.Schemas {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XML() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Schemas.XML", typeof(XML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;nfeProc versao=&quot;4.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///    &lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///        &lt;infNFe Id=&quot;NFe31231120855151000139650040000938509100660678&quot; versao=&quot;4.00&quot;&gt;
        ///            &lt;ide&gt;
        ///                &lt;cUF&gt;31&lt;/cUF&gt;
        ///                &lt;cNF&gt;10066067&lt;/cNF&gt;
        ///                &lt;natOp&gt;VENDA&lt;/natOp&gt;
        ///                &lt;mod&gt;65&lt;/mod&gt;
        ///                &lt;serie&gt;4&lt;/serie&gt;
        ///                &lt;nNF&gt;93850&lt;/nNF&gt;
        ///                &lt;dhEmi&gt;2023-11-01T01:14:2 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string NFCeNt2023_001 {
            get {
                return ResourceManager.GetString("NFCeNt2023_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;nfeProc versao=&quot;4.00&quot; xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///    &lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///        &lt;infNFe versao=&quot;4.00&quot; Id=&quot;NFe35231000000000000000000000000000000000000000&quot;&gt;
        ///            &lt;ide&gt;
        ///                &lt;cUF&gt;35&lt;/cUF&gt;
        ///                &lt;cNF&gt;18139565&lt;/cNF&gt;
        ///                &lt;natOp&gt;DEVOLUCAO DE COMPRA&lt;/natOp&gt;
        ///                &lt;mod&gt;55&lt;/mod&gt;
        ///                &lt;serie&gt;1&lt;/serie&gt;
        ///                &lt;nNF&gt;123&lt;/nNF&gt;
        ///                &lt;dhEmi&gt;2023-10-10T00:00:00-03:00&lt;/dhEmi&gt;
        ///            [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string NFeIpiDevolvido {
            get {
                return ResourceManager.GetString("NFeIpiDevolvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///&lt;!DOCTYPE schema
        ///PUBLIC &quot;-//W3C//DTD XMLSchema 200102//EN&quot; &quot;http://www.w3.org/2001/XMLSchema.dtd&quot;
        ///[
        ///&lt;!ATTLIST schema
        ///xmlns:ds CDATA #FIXED &quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///&lt;!ENTITY dsig &apos;http://www.w3.org/2000/09/xmldsig#&apos;&gt;
        ///&lt;!ENTITY % p &apos;&apos;&gt;
        ///&lt;!ENTITY % s &apos;&apos;&gt;
        ///]&gt;
        ///--&gt;
        ///&lt;!-- Schema for XML Signatures
        ///http://www.w3.org/2000/09/xmldsig#
        ///$Revision: 4 $ on $Date: 2004-12-16 12:08:17 -0500 (Thu, 16 Dec 2004) $ by $Author: marcgratacos $
        ///
        ///Copyright 2001 T [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
    }
}
