//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EficazFramework.SPED.Resources.Samples {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eSocial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eSocial() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EficazFramework.Resources.Samples.eSocial", typeof(eSocial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;eSocial xmlns=&quot;http://www.esocial.gov.br/schema/evt/evtInfoEmpregador/v_S_01_01_00&quot;&gt;
        /// &lt;evtInfoEmpregador Id=&quot;ID1123456780000002023061909493500001&quot;&gt;
        ///  &lt;ideEvento&gt;
        ///   &lt;tpAmb&gt;1&lt;/tpAmb&gt;
        ///   &lt;procEmi&gt;1&lt;/procEmi&gt;
        ///   &lt;verProc&gt;v_S_01_01_00&lt;/verProc&gt;
        ///  &lt;/ideEvento&gt;
        ///  &lt;ideEmpregador&gt;
        ///   &lt;tpInsc&gt;1&lt;/tpInsc&gt;
        ///   &lt;nrInsc&gt;12345678&lt;/nrInsc&gt;
        ///  &lt;/ideEmpregador&gt;
        ///  &lt;infoEmpregador&gt;
        ///   &lt;inclusao&gt;
        ///    &lt;idePeriodo&gt;
        ///     &lt;iniValid&gt;2023-06&lt;/iniValid&gt;
        ///    &lt;/i [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string S1000_v_S_01_01_01 {
            get {
                return ResourceManager.GetString("S1000_v_S_01_01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;eSocial xmlns=&quot;http://www.esocial.gov.br/schema/evt/evtInfoEmpregador/v02_04_02&quot;&gt;
        /// &lt;evtInfoEmpregador Id=&quot;ID1123456780000002018092508301200001&quot;&gt;
        ///  &lt;ideEvento&gt;
        ///   &lt;tpAmb&gt;1&lt;/tpAmb&gt;
        ///   &lt;procEmi&gt;1&lt;/procEmi&gt;
        ///   &lt;verProc&gt;v02_04_02&lt;/verProc&gt;
        ///  &lt;/ideEvento&gt;
        ///  &lt;ideEmpregador&gt;
        ///   &lt;tpInsc&gt;1&lt;/tpInsc&gt;
        ///   &lt;nrInsc&gt;12345678&lt;/nrInsc&gt;
        ///  &lt;/ideEmpregador&gt;
        ///  &lt;infoEmpregador&gt;
        ///   &lt;inclusao&gt;
        ///    &lt;idePeriodo&gt;
        ///     &lt;iniValid&gt;2018-07&lt;/iniValid&gt;
        ///    &lt;/idePeri [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string S1000_v02_04_02 {
            get {
                return ResourceManager.GetString("S1000_v02_04_02", resourceCulture);
            }
        }
    }
}
